# Generated by Django 3.0.6 on 2020-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200521_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='media_root/images'),
        ),
        migrations.DeleteModel(
            name='order_by_date',
        ),
    ]
