# Generated by Django 3.0.6 on 2020-05-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200523_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
