# Generated by Django 3.0.6 on 2020-05-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='addr',
        ),
    ]
