# Generated by Django 3.0.6 on 2020-05-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200524_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tests',
        ),
    ]
