# Generated by Django 3.0.6 on 2020-05-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_order_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
