# Generated by Django 3.0.6 on 2020-05-24 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200524_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 18, 18, 48, 471715, tzinfo=utc)),
        ),
    ]
