# Generated by Django 3.0.6 on 2020-05-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_order_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
    ]
