# Generated by Django 3.0.6 on 2020-05-24 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_orderitem_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
